--PERCENTAGE OF INFECTED PER POPULATION IN NIGERIA PER DAY

DROP TABLE IF EXISTS #COVID_NIGERIA
CREATE TABLE #COVID_NIGERIA
(
[LOCATION] VARCHAR(12),
[DATE] DATETIME,
[POPULATION] FLOAT,
[TOTAL CASES] FLOAT,
[NEW CASES] FLOAT,
[TOTAL DEATHS] FLOAT,
[NEW DEATHS]  FLOAT
)

INSERT INTO #COVID_NIGERIA
   SELECT LOCATION, DATE, POPULATION,TOTAL_CASES, NEW_CASES, TOTAL_DEATHS, NEW_DEATHS
   FROM [dbo].[COVID DEATHS]
   WHERE LOCATION  = 'NIGERIA'
SELECT *
FROM #COVID_NIGERIA

SELECT DATE, LOCATION, [TOTAL CASES], POPULATION, ([TOTAL CASES]/POPULATION)* 100 AS [%INFECTED PER POPULATION]
FROM #COVID_NIGERIA
GROUP BY  DATE, LOCATION, [TOTAL CASES], POPULATION
ORDER BY [%INFECTED PER POPULATION]

--PERCENTAGE OF DEATH PER POPULATION IN NIGERIA PER DAY

SELECT DATE, LOCATION, [TOTAL DEATHS], POPULATION, ([TOTAL DEATHS]/POPULATION)* 100 AS [%DEATHS PER POPULATION]
FROM #COVID_NIGERIA
GROUP BY  DATE, LOCATION, [TOTAL DEATHS], POPULATION
ORDER BY [%DEATHS PER POPULATION]

--TOTAL NUMBER OF INFECTED IN NIGERIA

SELECT LOCATION, POPULATION, SUM(CAST([NEW CASES] AS INT)) AS [TOTAL INFECTED]
FROM #COVID_NIGERIA
GROUP BY LOCATION, POPULATION
ORDER BY [TOTAL INFECTED]

--TOTAL NUMBER OF DEATHS IN NIGERIA 

SELECT LOCATION, POPULATION, SUM(CAST([NEW DEATHS] AS INT)) AS [TOTAL DEATHS]
FROM #COVID_NIGERIA
GROUP BY LOCATION, POPULATION
ORDER BY [TOTAL DEATHS]

--PERCENTAGE OF INFECTED IN NIGERIA

WITH [PERCENTAGE OF INFECTED] AS
(
    SELECT LOCATION, POPULATION, SUM(CAST([NEW CASES] AS INT)) AS [TOTAL INFECTED]
    FROM #COVID_NIGERIA
    GROUP BY LOCATION, POPULATION  
)
SELECT LOCATION, POPULATION, [TOTAL INFECTED], ([TOTAL INFECTED]/POPULATION)*100 AS [%INFECTED]
FROM [PERCENTAGE OF INFECTED]

--PERCENTAGE OF DEATH IN NIGERIA

WITH [PERCENTAGE OF DEATH] AS
(
   SELECT LOCATION, POPULATION, SUM(CAST([NEW DEATHS] AS INT)) AS [TOTAL DEATHS]
   FROM #COVID_NIGERIA
   GROUP BY LOCATION, POPULATION
)
SELECT LOCATION, POPULATION, [TOTAL DEATHS], ([TOTAL DEATHS]/POPULATION)*100 AS [%DEATHS]
FROM [PERCENTAGE OF DEATH]

--CHANCES OF INFECTION IN NIGERIA DUE TO COVID-19

SELECT LOCATION, POPULATION, (SUM([NEW CASES])/POPULATION)* 100 AS [CHANCES OF INFECTION]
FROM #COVID_NIGERIA
GROUP BY LOCATION, POPULATION
ORDER BY [CHANCES OF INFECTION]

--CHANCES OF DEATH IN NIGERIA DUE TO COVID-19

SELECT LOCATION, POPULATION, SUM([NEW DEATHS])/SUM([NEW CASES])* 100 AS [CHANCES OF DEATH]
FROM #COVID_NIGERIA
GROUP BY LOCATION, POPULATION
ORDER BY [CHANCES OF DEATH]

--COUNTRIES WITH HIGHEST INFECTED

SELECT LOCATION, POPULATION,  SUM(NEW_CASES) AS [TOTAL INFECTED]
FROM [dbo].[COVID DEATHS]
WHERE CONTINENT IS NOT NULL
GROUP BY LOCATION, POPULATION
ORDER BY [TOTAL INFECTED] DESC

--COUNTRIES WITH HIGHEST DEATH DUE TO COVID-19

SELECT LOCATION, POPULATION,  SUM(CAST(NEW_DEATHS AS NUMERIC)) AS [TOTAL DEATHS]
FROM [dbo].[COVID DEATHS]
WHERE CONTINENT IS NOT NULL
GROUP BY LOCATION, POPULATION
ORDER BY [TOTAL DEATHS] DESC

--CONTINENT WITH HIGHEST INFECTED

WITH INFECTED_COUNTRIES AS
(
    SELECT CONTINENT,LOCATION,POPULATION, SUM(CAST(NEW_CASES AS NUMERIC)) AS [TOTAL INFECTED PER COUNTRY]
    FROM [dbo].[COVID DEATHS]
    WHERE CONTINENT IS NOT NULL	
	GROUP BY CONTINENT, LOCATION, POPULATION	
)
SELECT CONTINENT, SUM(POPULATION) AS [TOTAL POPULATION PER CONTINENT], SUM([TOTAL INFECTED PER COUNTRY]) AS [TOTAL INFECTED PER CONTINENT], (SUM([TOTAL INFECTED PER COUNTRY])/SUM(POPULATION))* 100 AS [%INFECTED PER CONTINENT]
FROM INFECTED_COUNTRIES
GROUP BY CONTINENT
ORDER BY [TOTAL INFECTED PER CONTINENT] DESC

--CONTINENT WITH HIGHEST DEATH

WITH DEATH_COUNTRIES AS
(
    SELECT CONTINENT,LOCATION, POPULATION, SUM(CAST(NEW_DEATHS AS BIGINT)) AS [TOTAL DEATHS PER COUNTRY]
    FROM [dbo].[COVID DEATHS]
    WHERE CONTINENT IS NOT NULL	
	GROUP BY CONTINENT, LOCATION, POPULATION	
)
SELECT CONTINENT, SUM(POPULATION) AS [TOTAL POPULATION PER CONTINENT], SUM([TOTAL DEATHS PER COUNTRY]) AS [TOTAL DEATHS PER CONTINENT], (SUM([TOTAL DEATHS PER COUNTRY])/SUM(POPULATION))* 100 AS [%DEATHS PER CONTINENT]
FROM DEATH_COUNTRIES
GROUP BY CONTINENT
ORDER BY [TOTAL DEATHS PER CONTINENT] DESC

--TOTAL VACCINATIONS IN NIGERIA

WITH [TOTAL VACC IN NIGERIA] AS
(
    SELECT LOCATION, POPULATION, (SELECT SUM(CAST(NEW_VACCINATIONS AS numeric)) FROM [dbo].[COVID VACCINATIONS] WHERE LOCATION = 'NIGERIA') AS [TOTAL VACCINATIONS IN NIGERIA]
    FROM [dbo].[COVID VACCINATIONS]
    WHERE LOCATION = 'NIGERIA'
    GROUP BY LOCATION, POPULATION
)
SELECT LOCATION, POPULATION, [TOTAL VACCINATIONS IN NIGERIA], ([TOTAL VACCINATIONS IN NIGERIA]/POPULATION)*100 AS [% OF VACCINATED]
FROM [TOTAL VACC IN NIGERIA]

--TOTAL VACCINATIONS IN THE WORLD

DROP TABLE IF EXISTS #GLOBVAC
CREATE TABLE #GLOBVAC
(
LOCATION VARCHAR(100),
POPULATION NUMERIC,
[TOTAL VACCINATED] NUMERIC
)
INSERT INTO #GLOBVAC
SELECT  CVD.LOCATION, CVD.POPULATION, SUM(CAST(NEW_VACCINATIONS AS BIGINT)) [TOTAL VACCINATED]
FROM [dbo].[COVID DEATHS] AS CVD
 JOIN [dbo].[COVID VACCINATIONS] AS CVV
     ON CVD.LOCATION = CVV.LOCATION
	 AND CVD.DATE = CVV.DATE
	 WHERE CVD.CONTINENT IS NOT NULL
GROUP BY CVD.LOCATION, CVD.POPULATION
order by location

SELECT location, population, [TOTAL VACCINATED], ([TOTAL VACCINATED]/POPULATION) * 100 AS [% TOTAL VACCINATED]
FROM #GLOBVAC
GROUP BY  location, population, [TOTAL VACCINATED]
ORDER BY [% TOTAL VACCINATED] DESC


--CREATING VIEWS FOR VISUALIZATIONS
create view [COUNTRIES HIGHEST INFECTED] AS
SELECT LOCATION, POPULATION,  SUM(NEW_CASES) AS [TOTAL INFECTED]
FROM [dbo].[COVID DEATHS]
WHERE CONTINENT IS NOT NULL
GROUP BY LOCATION, POPULATION
--ORDER BY [TOTAL INFECTED] DESC

--COUNTRIES WITH HIGHEST DEATH DUE TO COVID-19 

CREATE VIEW [COUNTRIES HIGHEST DEATH  COVID-19] AS
SELECT LOCATION, POPULATION,  SUM(CAST(NEW_DEATHS AS NUMERIC)) AS [TOTAL DEATHS]
FROM [dbo].[COVID DEATHS]
WHERE CONTINENT IS NOT NULL
GROUP BY LOCATION, POPULATION
--ORDER BY [TOTAL DEATHS] DESC

--CONTINENT WITH HIGHEST DEATH 

CREATE VIEW [HIGHEST DEATH CONTINENT] AS
WITH DEATH_COUNTRIES AS
(
    SELECT CONTINENT,LOCATION, POPULATION, SUM(CAST(NEW_DEATHS AS BIGINT)) AS [TOTAL DEATHS PER COUNTRY]
    FROM [dbo].[COVID DEATHS]
    WHERE CONTINENT IS NOT NULL	
	GROUP BY CONTINENT, LOCATION, POPULATION	
)
SELECT CONTINENT, SUM(POPULATION) AS [TOTAL POPULATION PER CONTINENT], SUM([TOTAL DEATHS PER COUNTRY]) AS [TOTAL DEATHS PER CONTINENT], (SUM([TOTAL DEATHS PER COUNTRY])/SUM(POPULATION))* 100 AS [%DEATHS PER CONTINENT]
FROM DEATH_COUNTRIES
GROUP BY CONTINENT
--ORDER BY [TOTAL DEATHS PER CONTINENT] DESC

--CONTINENT WITH HIGHEST INFECTED

CREATE VIEW [HIGHEST INFECTED CONTINENT] AS
WITH INFECTED_COUNTRIES AS
(
    SELECT CONTINENT,LOCATION,POPULATION, SUM(CAST(NEW_CASES AS NUMERIC)) AS [TOTAL INFECTED PER COUNTRY]
    FROM [dbo].[COVID DEATHS]
    WHERE CONTINENT IS NOT NULL	
	GROUP BY CONTINENT, LOCATION, POPULATION	
)
SELECT CONTINENT, SUM(POPULATION) AS [TOTAL POPULATION PER CONTINENT], SUM([TOTAL INFECTED PER COUNTRY]) AS [TOTAL INFECTED PER CONTINENT], (SUM([TOTAL INFECTED PER COUNTRY])/SUM(POPULATION))* 100 AS [%INFECTED PER CONTINENT]
FROM INFECTED_COUNTRIES
GROUP BY CONTINENT
--ORDER BY [TOTAL INFECTED PER CONTINENT] DESC



